version: '3.9'
services:
  web:
    build: .
    ports:
     - "8080:8080"
    links:
     - db
    environment:
     DB_URL: 'postgres://postgres:postgres@db/postgres?sslmode=disable'
  db:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: postgres
